import { Participant, DrawResult, GiveawayConfig } from '@/types/participant'

// Sample mock data for development
export const mockParticipants: Participant[] = [
  {
    id: '1',
    fbUserId: 'user_001',
    fbUserName: 'สมชาย มานะ',
    fbProfileUrl: 'https://facebook.com/somchai.mana',
    fbProfilePicture: '',
    commentText: 'ไปด้วยกันนะ @นิดา สวยงาม อยากไปฟังดนตรีด้วยกัน เคยไปด้วยกันมาแล้ว สนุกมาก! #AngThongMusicLove',
    commentTime: new Date('2026-01-15T10:30:00'),
    taggedFriends: [{ name: 'นิดา สวยงาม', profileUrl: 'https://facebook.com/nida' }],
    hashtags: ['#AngThongMusicLove'],
    textLength: 85,
    status: 'passed',
    failReasons: [],
    conditions: {
      hasLikedPage: true,
      hasSharedPost: true,
      hasTaggedFriend: true,
      hasHashtag: true,
      hasReason: true,
    },
  },
  {
    id: '2',
    fbUserId: 'user_002',
    fbUserName: 'มานี รักเพลง',
    fbProfileUrl: 'https://facebook.com/manee.rukpleng',
    fbProfilePicture: '',
    commentText: '@ใจดี มาด้วยกันเถอะ! อยากฟังเพลงสดๆ ใต้แสงดาว เราชอบดนตรีเหมือนกัน #AngThongMusicLove',
    commentTime: new Date('2026-01-15T11:45:00'),
    taggedFriends: [{ name: 'ใจดี', profileUrl: 'https://facebook.com/jaidee' }],
    hashtags: ['#AngThongMusicLove'],
    textLength: 78,
    status: 'passed',
    failReasons: [],
    conditions: {
      hasLikedPage: true,
      hasSharedPost: true,
      hasTaggedFriend: true,
      hasHashtag: true,
      hasReason: true,
    },
  },
  {
    id: '3',
    fbUserId: 'user_003',
    fbUserName: 'วิชัย เก่งมาก',
    fbProfileUrl: 'https://facebook.com/wichai.geng',
    fbProfilePicture: '',
    commentText: '@เพื่อนดี #AngThongMusicLove',
    commentTime: new Date('2026-01-15T12:00:00'),
    taggedFriends: [{ name: 'เพื่อนดี' }],
    hashtags: ['#AngThongMusicLove'],
    textLength: 28,
    status: 'failed',
    failReasons: ['ข้อความสั้นเกินไป (ต้องมากกว่า 30 ตัวอักษร)'],
    conditions: {
      hasLikedPage: true,
      hasSharedPost: true,
      hasTaggedFriend: true,
      hasHashtag: true,
      hasReason: false,
    },
  },
  {
    id: '4',
    fbUserId: 'user_004',
    fbUserName: 'ศรีสุดา แสงทอง',
    fbProfileUrl: 'https://facebook.com/srisuda.sang',
    fbProfilePicture: '',
    commentText: 'อยากไปมากๆ เลยค่ะ ฟังเพลงใต้แสงดาว บรรยากาศดีมาก',
    commentTime: new Date('2026-01-15T13:20:00'),
    taggedFriends: [],
    hashtags: [],
    textLength: 46,
    status: 'failed',
    failReasons: ['ไม่มีแท็กเพื่อน', 'ไม่มี #AngThongMusicLove'],
    conditions: {
      hasLikedPage: true,
      hasSharedPost: true,
      hasTaggedFriend: false,
      hasHashtag: false,
      hasReason: true,
    },
  },
  {
    id: '5',
    fbUserId: 'user_005',
    fbUserName: 'ประภา ชื่นใจ',
    fbProfileUrl: 'https://facebook.com/prapa.chuenjai',
    fbProfilePicture: '',
    commentText: '@น้องนุ่น มาเดินทางไกลไปด้วยกัน วันนี้เราสองคนจะได้ฟังเพลงโปรดด้วยกัน! #AngThongMusicLove 💕',
    commentTime: new Date('2026-01-15T14:00:00'),
    taggedFriends: [{ name: 'น้องนุ่น', profileUrl: 'https://facebook.com/nongnun' }],
    hashtags: ['#AngThongMusicLove'],
    textLength: 82,
    status: 'passed',
    failReasons: [],
    conditions: {
      hasLikedPage: true,
      hasSharedPost: true,
      hasTaggedFriend: true,
      hasHashtag: true,
      hasReason: true,
    },
  },
  {
    id: '6',
    fbUserId: 'user_006',
    fbUserName: 'ธีรพงษ์ รักดนตรี',
    fbProfileUrl: 'https://facebook.com/teerapong.music',
    fbProfilePicture: '',
    commentText: 'ชวน @แอนจี้ ไปดูคอนเสิร์ตด้วยกัน เพราะเราทั้งคู่ชอบฟังเพลงสดมาก และงานนี้น่าจะสนุกสุดๆ #AngThongMusicLove 🎵',
    commentTime: new Date('2026-01-15T14:30:00'),
    taggedFriends: [{ name: 'แอนจี้', profileUrl: 'https://facebook.com/angie' }],
    hashtags: ['#AngThongMusicLove'],
    textLength: 95,
    status: 'passed',
    failReasons: [],
    conditions: {
      hasLikedPage: true,
      hasSharedPost: true,
      hasTaggedFriend: true,
      hasHashtag: true,
      hasReason: true,
    },
  },
  {
    id: '7',
    fbUserId: 'user_007',
    fbUserName: 'กมลวรรณ เพลงเพราะ',
    fbProfileUrl: 'https://facebook.com/kamonwan.pleng',
    fbProfilePicture: '',
    commentText: '@พี่ปอ มาด้วยกันนะคะ #AngThongMusicLove',
    commentTime: new Date('2026-01-15T15:00:00'),
    taggedFriends: [{ name: 'พี่ปอ' }],
    hashtags: ['#AngThongMusicLove'],
    textLength: 38,
    status: 'failed',
    failReasons: ['ข้อความสั้นเกินไป (ต้องมากกว่า 30 ตัวอักษร)'],
    conditions: {
      hasLikedPage: null,
      hasSharedPost: null,
      hasTaggedFriend: true,
      hasHashtag: true,
      hasReason: false,
    },
  },
  {
    id: '8',
    fbUserId: 'user_008',
    fbUserName: 'รัตนาภรณ์ สดใส',
    fbProfileUrl: 'https://facebook.com/rattana.sodsai',
    fbProfilePicture: '',
    commentText: 'ไปกันเถอะ @น้องเบียร์ ฉันรอคอยคอนเสิร์ตนี้มานานมาก อยากไปสัมผัสบรรยากาศดีๆ ด้วยกัน! 🌟 #AngThongMusicLove',
    commentTime: new Date('2026-01-15T16:45:00'),
    taggedFriends: [{ name: 'น้องเบียร์', profileUrl: 'https://facebook.com/nongbeer' }],
    hashtags: ['#AngThongMusicLove'],
    textLength: 89,
    status: 'passed',
    failReasons: [],
    conditions: {
      hasLikedPage: true,
      hasSharedPost: true,
      hasTaggedFriend: true,
      hasHashtag: true,
      hasReason: true,
    },
  },
]

export const mockDrawResults: DrawResult[] = [
  {
    id: 'draw_001',
    timestamp: new Date('2026-01-20T18:00:00'),
    winner: mockParticipants[0],
    totalParticipants: 8,
    qualifiedParticipants: 5,
    seed: 'aB3c5D7e9F1g2H4j6K8',
    drawnBy: 'Admin',
  },
]

export const defaultConfig: GiveawayConfig = {
  eventName: 'Angthong Music Love 2026',
  postUrl: 'https://facebook.com/angthongmusicfest/posts/123456',
  requiredHashtag: '#AngThongMusicLove',
  enableHashtag: true,
  minTaggedFriends: 1,
  enableTag: true,
  minTextLength: 30,
  enableMinLength: true,
  likeVerification: 'skip',
  shareVerification: 'skip',

}

export const mockStats = {
  totalComments: 8,
  qualified: 5,
  disqualified: 3,
  pending: 0,
}
